### PR TITLE
Workflow-details page

### PR DESCRIPTION
**Pull request by Sinclert**
Work in progress with the Workflow-Details page. As this is the most complex page, it will take time, but I would like to have a basic version of it by **August 14th**, as I am supposed to give a flash talk about my contribution to the project.

It is also important to consider that it will work properly when all `reana-server` endpoints will use [JWT](https://jwt.io). This work is on progress too.

### CODE REVIEW

**Comment by lukasheinrich** [comment]
Hi @Sinclert, did we settle on vis.js or is this just a placeholder that might be changed?

**Comment by Sinclert** [comment]
Hi @lukasheinrich ! No, **Vis.js is not settled**, it is just a placeholder for the first steps of the `Workflow-Details` page implementation.

Last days I have been focusing on completing navigation using [React-Router-DOM](https://www.npmjs.com/package/react-router-dom). Soon I will start considering the different Graph visualisation libraries, which will usually go in a different PR :)

**Comment by lukasheinrich** [comment]
ok great :)

if there are any mock ups what the pages look like righht now, I'd be curious to see. 

Thanks!

**Comment by lukasheinrich** [comment]
Hi @Sinclert is there some way to follow this visually (mocks, screenshots?)

**Comment by Sinclert** [comment]
Hi @lukasheinrich ,

We are not currently uploading any development screenshot to any platform. However, I can share with the current `workflow-details` page looks like for an example workflow :)

screen shot 2018-08-22 at 09 28 06

**Comment by lukasheinrich** [comment]
thanks @Sinclert that was exactly what I was looking for. looks great!

**Pull request merged**
